name: Prowler Setup

on:
  push:
    branches:
      - main
      
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  install_prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::924144197303:role/github-oidc-role-prowler
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: install pip packages
        run: |
          sudo su
          sudo apt-get update
          sudo apt install python3-pip -y
          sudo pip install prowler
          ulimit -n 4096
          prowler aws
        continue-on-error: true
        
      - name: Transfering files to s3 bucket
        run: |
          export DATE=$(date +"%d-%m-%y_%H-%M-%S")
          aws s3 cp --recursive /home/runner/work/prowler/prowler/output s3://prowler-862023-test-private/$DATE
          
          
