name: Prowler Setup

on:
  push:
    branches:
      - main

jobs:
  install_prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: install pip packages
        run: |
          sudo su
          sudo apt-get update
          sudo apt install python3-pip -y
          sudo pip install prowler
          ulimit -n 4096
          prowler aws
        continue-on-error: true
        
      - name: run ls
        run: |
          ls
          ls output
        
      - name: Sending files to S3 bucket
        run: |
          aws s3 cp --recursive ~/output s3://prowler-862023-test-private
